crowdsupport:
  version: @project.version@
  db:
    type: h2
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
flyway:
  locations:
    - db/migration/common
    - db/migration/${crowdsupport.db.type}
spring:
  datasource:
    url: ${crowdsupport.db.url}
    username: ${crowdsupport.db.username}
    password: ${crowdsupport.db.password}
  thymeleaf:
    mode: HTML5
  jackson:
    mapper:
      use_getters_as_setters: false
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      write_dates_as_timestamps: false
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
logging:
  level:
    org.outofrange.crowdsupport.spring.ApiVersionRequestMappingHandlerMapping: WARN

---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: false # Could be useful, but is annoying most of the times
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent_output: true
server:
  port: 8080
logging:
  level:
    org.outofrange.crowdsupport: TRACE