spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  thymeleaf:
    mode: HTML5
  jackson:
    serialization:
      write_dates_as_timestamps: false
server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
crowdsupport:
  version: @project.version@
  token:
    secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%-8X{requestHash}]){magenta} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint}%clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent_output: true
server:
  port: 8080
logging:
  level:
    org.outofrange.crowdsupport: TRACE