spring:
  profiles:
     active: prod

---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
database:
  driver: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:

---

spring:
  profiles: prod

database:
  driver: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: