spring:
  thymeleaf:
    mode: HTML5
  jackson:
    serialization:
      write_dates_as_timestamps: false
---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jackson:
    serialization:
      indent_output: true

---

spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
server:
  port: 80